name       : haskell-hscolour
version    : 1.24.1
release    : 1
source     :
    - http://hackage.haskell.org/package/hscolour-1.24.1/hscolour-1.24.1.tar.gz : e46fe3de8ed6f96e2216b94b7608d01919bc86b15dd8d0ec7e71c0e7e5bf79c8
license    : BSD-3-Clause
component  : programming
summary    : hscolour is a small Haskell script to colourise Haskell code.
description: |
    hscolour is a small Haskell script to colourise Haskell code.
builddeps  :
    - ghc
setup      : |
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 hscolour-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/hscolour-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/hscolour-$version/*.a
    mv $installdir/usr/share/x86_64-linux-ghc-8.0.1 $installdir/usr/share/ghc-8.0.1