name       : haskell-hscolour
version    : 1.24.4
release    : 4
source     :
    - https://hackage.haskell.org/package/hscolour-1.24.4/hscolour-1.24.4.tar.gz : 243332b082294117f37b2c2c68079fa61af68b36223b3fc07594f245e0e5321d
license    : BSD-3-Clause
component  : programming.haskell
summary    : hscolour is a small Haskell script to colourise Haskell code.
description: |
    hscolour is a small Haskell script to colourise Haskell code.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
    mv $installdir/usr/share/%ARCH%-linux-ghc-$GHCV $installdir/usr/share/ghc-$GHCV
