name       : haskell-hscolour
version    : 1.24.1
release    : 2
source     :
    - http://hackage.haskell.org/package/hscolour-1.24.1/hscolour-1.24.1.tar.gz : e46fe3de8ed6f96e2216b94b7608d01919bc86b15dd8d0ec7e71c0e7e5bf79c8
license    : BSD-3-Clause
component  : programming.haskell
summary    : hscolour is a small Haskell script to colourise Haskell code.
description: |
    hscolour is a small Haskell script to colourise Haskell code.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
    mv $installdir/usr/share/%ARCH%-linux-ghc-$GHCV $installdir/usr/share/ghc-$GHCV
